# Generated by Django 3.1 on 2020-09-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_faceactscri_facebookaction_facebookactionscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
